name: Deploy PHP Website to AWS EC2 (Generate Key Pair)

on: workflow_dispatch

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Deployment Repo
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.GAURAV_SECRET_KEY_ID }}
        aws-secret-access-key: ${{ secrets.GAURAV_SECRET_KEY_PASS }}
        aws-region: ap-south-1

    - name: Create Key Pair (lampkey)
      id: create-key
      run: |
        echo "Creating EC2 Key Pair lampkey..."
        aws ec2 delete-key-pair --key-name lampkey --region ap-south-1 || true
        aws ec2 create-key-pair \
          --key-name lampkey \
          --key-type rsa \
